NAME = whetstone
SRCS = whetstone.c
include $(AM_HOME)/Makefile.app


# CFLAGS += -static -L/nfs/share/opt/riscv/sysroot/usr/lib /nfs/share/opt/riscv/sysroot/usr/lib/libm.a /nfs/share/opt/riscv/sysroot/usr/lib/libc.a
LINK_FILES += /nfs/share/opt/riscv/sysroot/usr/lib/libm.a /nfs/share/opt/riscv/sysroot/usr/lib/libc.a